version: "3"
services:
  phpfpm:
    build:
      context: ./docker/phpfpm
    volumes:
      - ./src:/usr/src/fetcher
    networks:
      - webnetwork
    hostname: phpfpm  

networks:
  webnetwork:
    name: tbar_meetup 
    driver: bridge