FROM php:8-fpm

# Use RUN to setup the image

# RUN apt-get update && apt-get -y install curl vim
# RUN echo 'memory_limit = 2G' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini

WORKDIR /usr/src/fetcher